# Generated by Django 3.0.3 on 2020-07-25 19:01

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Coordenadas')),
            ],
        ),
    ]
