# Generated by Django 2.1 on 2020-06-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_auto_20200625_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cedula',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
