# Generated by Django 2.1 on 2020-06-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_alumno_cedula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
