# Generated by Django 2.1 on 2020-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0006_auto_20200626_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
