# Generated by Django 3.0.3 on 2020-07-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0009_classroom_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='cc_file',
            field=models.FileField(blank=True, null=True, upload_to='Alumnos/', verbose_name='Documento'),
        ),
    ]
