# Generated by Django 3.0.3 on 2020-07-25 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('alumnos', '0010_alumno_cc_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuela.Escuela'),
        ),
    ]
